[package]
name = "fsc_compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
fsc_assembler = { path = "../fsc_assembler" }
fsc_codegen = { path = "../fsc_codegen" }
fsc_diagnostics = { path = "../fsc_diagnostics" }
fsc_parse = { path = "../fsc_parse" }
fsc_sema = { path = "../fsc_sema" }

[lints]
workspace = true
